### ISSUE TITLE
bson: Document is corrupted

### ISSUE THREAD

**Issue by dvyukov** [go-mgo/mgo#117]
The following program crashes with "Document is corrupted" panic. It should not happen as the first Unmarshal and Marshal succeed. So it seems that either Unmarshal or Marshal lose some information along the way and is not idempotent.

```go
package main

import "gopkg.in/mgo.v2/bson"

func main() {
	data := []byte("!\x00\x00\x00\x01000000000000000000\x0000000000\x00")
	v := new(S)
	if bson.Unmarshal(data, v) != nil {
		return
	}
	data1, err := bson.Marshal(v)
	if err != nil {
		return
	}
	v1 := new(S)
	if err := bson.Unmarshal(data1, v1); err != nil {
		panic(err)
	}
}

type S struct {
	W bson.Raw
}
```
on commit 3569c88

discovered with https://github.com/dvyukov/go-fuzz

**Comment by niemeyer** [comment]
The issue here is that bson.Raw is a bit loose when marshaling. The code using it should by itself make sure that what is being provided is valid, as the bson package will pretend it is. In this specific case, the error is being triggered by the fact the Unmarshal operation did not have any information for the field, so left it empty. When marshaling it, it got incorrectly marshaled as a document, which cannot be empty.

That said, we can do better in this scenario at least, by preventing code from marshaling such empty documents incorrectly. I'll add an explicit check to make sure this won't happen.

**Comment by dvyukov** [comment]
In the tests I usually check that anything that is Unmarshalled successfully can as well be Marshalled later. That is, tests look like:

if !Unmarshal { return }
if !Marshal { panic }
if !Unmarshal {panic }
if result of first and second Unmarshal differ { panic }

That's the best I can do in fuzzing tests (which have to deal with incorrect inputs).
As far as I understand, after this change the Marshal will fail. Which will fail my tests.
Why is not it possible for Marshal to produce the same binary representation that was feed into Unmarshal? This looks like the most sensible option to me. Or, if the data feed into the first Unmarshal was incorrect (can't possibly be marshalled), then the first Unmarshal should have been produced an error.

**Comment by niemeyer** [comment]
Not necessarily. It's common in Go to throw away information when unmarshaling data into a struct that has only part of the fields. In the example above, there's no "w" field in the provided data. Instead, it represents this valid document:

    map[string]interface{}{"000000000000000000": 1.398043286095289e-76}

So, when you try to unmarshal this onto this struct:

    struct{ W bson.Raw }

It drops the unknown field, and keeps the original struct unchanged, which is a correct operation.

Then, when it tries to marshal that again. That is an error, because W is a broken document (Kind 0 and Data set to []byte(nil)). If W was something else, say an int, it would marshal correctly, and into a different document than the originating one.

So Marshal and Unmarshal are not bijective, in bson or in other struct-handling marshalers.

**Comment by dvyukov** [comment]
I understand that Unmarshal can drop unknown fields. But the following still must work when Unmarshal drops unknown fields (and it does with encoding/{json, xml, gob}:

if !Unmarshal { return }
if !Marshal { panic }
if !Unmarshal {panic }
if result of first and second Unmarshal differ { panic }


But now the following makes sense:
> That is an error, because W is a broken document (Kind 0 and Data set to []byte(nil)).
You are saying that unless I fill in something into the document, the object won't be marshalled, right?

**Comment by niemeyer** [comment]
Right, that sequence is also valid for bson, and indeed bson.Raw is broken unless it's filled up with some data, which would prevent the Marshal from working if the first Unmarshal didn't fill it up properly.

**Comment by dvyukov** [comment]
Got it, thanks.

**Comment by niemeyer** [comment]
Btw, you might use `bson:",omitempty"` there to avoid the error.

**Comment by dvyukov** [comment]
Are you sure that omitempty works in this case?
I am getting ```panic: Attempted to marshal empty Raw document``` for the following struct:
```
type S struct {
	A int
	B string
	C float64
	D []byte
	E bool   `bson:"E1"`
	F uint8  `bson:",omitempty"`
	G S1
	H *S2
	I *int
	J *string
	K **int
	L **string
	M **S2
	N S1          `bson:",inline"`
	O int64       `bson:",minsize"`
	P bson.Binary `bson:",omitempty"`
	Q bson.D      `bson:",omitempty"`
	R interface{}
	S int
	T bson.JavaScript `bson:",omitempty"`
	U bson.M          `bson:",omitempty"`
	V bson.MongoTimestamp
	W bson.Raw  `bson:",omitempty"`
	X bson.RawD `bson:",omitempty"`
	Z bson.M    `bson:",inline"`
}
```

**Comment by niemeyer** [comment]
Assuming you're using go-fuzz, if bson.Raw is partly filled up, with a non-zero Kind but zero Data, it would still break this way because the struct is not actually "empty". Could that be the case?

**Comment by dvyukov** [comment]
If Unmarshal can partially fill the raw and don't fail, then yes, I can get partially filled raw.
I am effectively unmarshalling a random blob into the struct.

**Comment by niemeyer** [comment]
No, you are right, that shouldn't be possible. Do you have the offending code?

Revision 7d0c3292 adds a test ensuring omitempty works with Raw.

**Comment by dvyukov** [comment]
@niemeyer filed a separate issue #120 for that
