### ISSUE TITLE
bson.Unmarshal() does not support slices of generic types

### ISSUE THREAD

**Issue by liviosoares** [go-mgo/mgo#119]
Hi Gustavo,

We have started experimenting with using your bson package, independent of mgo, for serialization of data in our system. Initial experiments show that is quite nice, and has two big advantages from our point of view: (1) works great for generic Go data (even better than JSON, given the ',inline' support), and (2) has been performing more efficiently than JSON serialization for large objects. We are aware of other popular serialization packages, but most have a downside: require IDL, not schema-free, require pre-generated code, no great support for Go reflection, etc.

In any case, we ran into one case where bson.Unmarshal() did not work for us. Here is an minimal example:

```
package main
import "fmt"
import "gopkg.in/mgo.v2/bson"
func main() {
	slice1 := []int{0, 1}
	b, err := bson.Marshal(slice1)
	if err != nil {
		fmt.Println("error: ", err)
		return
	}
	var slice2 []int
	err = bson.Unmarshal(b, &slice2)
	if err != nil {
		fmt.Println("error: ", err)
		return
	}
	fmt.Println(slice2)
}
```

I understand that bson.Unmarshal() was written with bson.D in mind. But it would be useful to be able to get the above case working. I've made a change to decode.go, readDocTo() method, and got the above example to work:

```
diff --git a/bson/decode.go b/bson/decode.go
index bdd2e02..d95c4fd 100644
--- a/bson/decode.go
+++ b/bson/decode.go
@@ -219,6 +219,10 @@ func (d *decoder) readDocTo(out reflect.Value) {
                case typeRawDocElem:
                        origout.Set(d.readRawDocElems(outt))
                        return
+               default:
+                       slice := d.readSliceDoc(outt)
+                       origout.Set(reflect.ValueOf(slice))
+                       return
                }
                fallthrough
        default:
```

However, since I'm far from familiar with the code, the probability of this being the right way to implement this fix is low :-)

Would appreciate some guidance on this matter.

**Comment by niemeyer** [comment]
Hi Livio,

This is indeed not supported by the BSON specification, because the only type of value that exists at the top level is a structure (or a "document" according to the spec).

It's very easy to workaround this by simply putting your value under a specific field of the document, though. As an added bonus, this strategy will also allow you to extend the value in the future with further logic that was not anticipated, while preserving compatibility (imagine having a "version" field in addition to the content itself, for example). 

As a hint for future bug reports, please mention explicitly what you expected the code to be doing, and what it is doing instead, so the reader doesn't have to dig into the logic and attempt to infer.
