### ISSUE TITLE
Need interfaces for unit testing

### ISSUE THREAD

**Issue by hjkelly** [go-mgo/mgo#127]
I'm trying to unit test some non-trivial code that hits the database. It seems like unit testing in Go necessitates interfaces, so I structured my functions around my own interfaces that `mgo`'s  `Database`, `Collection`, and `Query` structs satisfy.

However, when testing things like `myCollection.Find(...).All(...)`, I hit a roadblock that I hadn't anticipated (being relatively new to Go): Because the real Collection.Find function will always return `*mgo.Query`, it doesn't satisfy the interface I had to write for my tests. In other words, it seems that the function signature needs to be the same in every relevant interface and in every definition of the functions/methods that satisfy that interface.

Is there a reason `mgo`'s code isn't built on interfaces like this? Perhaps the approach I'm taking isn't really idiomatic for Go?

If this would be a valuable addition, I'd be more than happy to work on a pull request.

**Comment by niemeyer** [comment]
If it was idiomatic for Go to never return a struct from a function or method, then there would be no need to support that in the language.

If you want to mock some specific aspect of your application, I would recommend doing it at a higher level than the database access layer, even because that layer should actually be tested against a real database to make sure the interaction actually works. Otherwise you may well get passing tests which in practice do not work, because complex interactions are being mocked away in improper ways.
