### ISSUE TITLE
mgo does not write after db.fsyncUnlock

### ISSUE THREAD

**Issue by muhammadn** [go-mgo/mgo#161]
After trying to enable writes back with db.fsyncUnlock, it seems that i have to restart the golang code to write again because mgo driver still thinks that the mongodb is locked.

**Comment by priithaamer** [comment]
We are facing somewhat similar issue. Not 100% sure if this is related to locked database though. We have web service written in Go that does around 50 mongodb commands per second, most of them are updates.

After a while (it could be days, weeks or even months), something happens that causes all queries to return empty responses (queries do not fail but nothing is read / written) and we are having hard time figuring out how to debug this. Restarting the process fixes the problem immediately.

We are using the single session at all times, not sure if this is a good idea. Here's how we initialize mgo session in the app:

```go
sess, err := mgo.Dial(config.Mongourl)

if err != nil {
	panic(err)
}
mgo_session = *sess
mgo_session.SetSafe(&mgo.Safe{})

db := mgo_session.DB("")
```

Each web service request does around 10 upserts to database, some requests do reading as well.

MongoDB is hosted in Compose. So it is in different datacenter and also could be some sort of networking issue. Does anyone have any ideas how we should approach debugging this issue?

**Comment by niemeyer** [comment]
@muhammadn The mgo driver doesn't have any special logic for fsync-locking/unlocking. It simply runs the respective server command. This is the full implementation of FsyncLock:

    return s.Run(bson.D{{"fsync", 1}, {"lock", true}}, nil)

If the Go application behaves as if the server is still locked, that's because it really is and something else is wrong.

@priithaamer Please mail the list about your issue so this can be discussed.
