### ISSUE TITLE
Not able to use hostnames with AAAA records

### ISSUE THREAD

**Issue by tomponline** [go-mgo/mgo#162]
Hi,

Since https://github.com/go-mgo/mgo/issues/153 it is no longer possible to use hostnames with AAAA records with the mgo driver.

**Comment by niemeyer** [comment]
Sorry for the trouble. It was well known that this particular configuration would break, and I generally don't do such partial fixes, but this is a special case as we had several developers complaining of the breakage with Go 1.5, so we had to take action quickly and that was the short term alternative.

We cannot special case localhost because this is just a symptom, not the actual issue. The real problem is that the resolution behavior has changed in 1.5, and thus I did a fix to bring back the correctness of IPv4 resolution, which is by far the most used, and then started to bring back the correctness of IPv6 resolution. The first step was already done: if you use an IPv6 literal address, it should work fine. I will now fix actual resolution and ping you so you have a chance to test it before it goes live, if that's okay?

**Comment by tomponline** [comment]
@niemeyer no problem, we would be happy to test any changes you have.

Is the issue that Go is now preferring IPv6 addresses to connect to if they are resolving in the DNS, and you must now try to connect to it, and if it fails to connect then fallback to doing an IPv4 only DNS lookup and connect attempt?

Thanks

**Comment by tomponline** [comment]
@niemeyer can you use the new DualStack variable in go 1.5

```
    44		// DualStack enables RFC 6555-compliant "Happy Eyeballs" dialing
    45		// when the network is "tcp" and the destination is a host name
    46		// with both IPv4 and IPv6 addresses. This allows a client to
    47		// tolerate networks where one address family is silently broken.
    48		DualStack bool
```

https://golang.org/src/net/dial.go

Looks like it would work with DialTimeout too

**Comment by niemeyer** [comment]
Tom, can you please test the changes in v2-unstable and see if it fixes the problem for you?

Thanks again.

**Comment by niemeyer** [comment]
@tomponline, can you please test the changes in v2-unstable and see if it fixes the problem for you?

Thanks again.

**Comment by tomponline** [comment]
@niemeyer wil do thanks!

**Comment by niemeyer** [comment]
Any news Tom? I'd like to release the next stable, but would be great to have your review on this.

**Comment by niemeyer** [comment]
Any news on this @tomponline? Would like to release the next stable, but would be great to have your review on this first.

**Comment by tomponline** [comment]
@niemeyer I did take a look at it yesterday, but it took quite a bit longer than I was expecting as I had to change all the references in our imports for mgo to mgo-unstable.

I'm also a bit nervous about putting all the other unstable changes live into production to test it.

Can you advise if I am 'doing it wrong' and how I should just test that single change?

**Comment by niemeyer** [comment]
If you'd like to simply patch your stable mgo.v2 with that one change, that would work for me as well. All you should need to change is to copy/paste the `resolveAddr` function inside cluster.go from unstable into your stable branch:

https://github.com/go-mgo/mgo/blob/2f3a9b3f/cluster.go#L412

**Comment by tomponline** [comment]
@niemeyer ok I'll give that a go  thanks

**Comment by robnorman** [comment]
Hi @niemeyer I've been testing this patch with @tomponline and it works just fine here - thanks for the fix.

**Comment by tomponline** [comment]
@niemeyer any ideas when this will be merged into v2 branch? cheers

**Comment by niemeyer** [comment]
This week still, if all goes well.
