### ISSUE TITLE
"Closed Explicitly" error

### ISSUE THREAD

**Issue by Netherdrake** [go-mgo/mgo#166]
I have a Docker cluster running 10 web services (of the same kind). They are all using MongoDB, among other things for data persistence.

This is the code that gets called from `main()`, when the service is booting up:

```
// Init establishes a connection with MongoDB instance.
func Init(mongoURL string) *mgo.Session {
	mongo, err := mgo.Dial(mongoURL)
	misc.PanicIf(err)

	// make sure we are strongly consistent
	mongo.SetMode(mgo.Strong, true)

	// update global state
	db = mongo
	Entries = db.DB("").C("entries")
	Channels = db.DB("").C("channels")
	Settings = db.DB("").C("settings")
	Metadata = db.DB("").C("metadata")

	// only use this on first load, to confirm the settings are there
	// every refresh should be done via UpdateGlobalSettings (thread-safe)
	GlobalSettings = &GlobalSettingsStruct{}
	GlobalSettings.Init()

	return mongo
}
```

So basically the API and the workers just use global variables such as `Entries`, `Settings`, etc.

After running for a while, the service stopped working properly. Every mongo action, such as `Entries.find(...)` returns an err of: `Closed Explicitly`.

What does that mean? Should I be refreshing the mongoDB connection periodically or should I make it close and re-establish connection with each request?

The app is performance oriented, so despite mongo connection being down, everything is still up and running as everything operates on in-memory or cluster cache. I don't want to do something stupid that delays processing.

Cheers

**Comment by niemeyer** [comment]
The code you show above is fine by itself, and that error could mean different things, but one good guess is that there was a fallover and pre-existent connections were closed for resync.

That said, this should be a one-off situation. The application should be immediately able to reconnect and restore its working state. The only thing mgo requires is for the error to be acknowledged by the app if it was in the middle of something so that incorrect behavior doesn't go unperceived.

There are two easy ways to organize the application to do that:

1. If the application is organized after some sort of loop, call Refresh on the session at the end of each iteration of the loop. This makes it discard (or put back in the pool, if the connection is good) the connection it's holding, and pick a new one when necessary. 

2. If handling multiple independent requests concurrently use an independent session for each request by calling session.Copy on the master session whenever a new session is needed, and then call session.Close when done with it. This also pools connections properly, and means using multiple connections to the database when necessary.

Your case sounds like the second one.

**Comment by Netherdrake** [comment]
Thank you Gustavo,

I have started implementing `session.Copy`. Unfortunately, this is not a webapp, so I cant just stick it into `net/http middleware`.

I made this little helper function:
```
// Users of this method have to close the sessions
func CopySession(collectionName string) (sesion *mgo.Session, collection *mgo.Collection) {
	session := Session.Copy()
	// defer session.Close()

	collection = session.DB("").C(collectionName)

	return session, collection
}

```

The `Session` object comes from a global variable and is initialised as soon as the service starts in `main()`.

I am wondering if calling the helper function `CopySession` is thread-safe (calling it from multiple goroutines, whilst the method makes a copy from global variable).

Cheers

**Comment by niemeyer** [comment]
Yes, sessions are concurrency-safe.

**Comment by opalfroot** [comment]
Just a question - is it safe to use an Iter pointer in multiple goroutines?

**Comment by niemeyer** [comment]
Yes, that's safe.

**Comment by skytask** [comment]
I have same problem here.
In my app in start-up i create a session and it's may be stay unuse until 5 days, and after 5 days when i want use that session i get `Closed Explicitly` !

Is it for mongodb close that session or ... ???
