### ISSUE TITLE
unrecoverable panic when DialWithTimeout fails in server.go

### ISSUE THREAD

**Issue by jackgr** [go-mgo/mgo#218]
I'm seeing a panic in a goroutine forked within mgo v2 when DialWithTimeout fails in server.go.

Here's the offending code at https://github.com/go-mgo/mgo/blob/v2/server.go#L164

		conn, err = net.DialTimeout("tcp", server.ResolvedAddr, timeout)
		if tcpconn, ok := conn.(*net.TCPConn); ok {
			tcpconn.SetKeepAlive(true)
		} else {
			panic("internal error: obtained TCP connection is not a *net.TCPConn!?")
		}

The panic occurs because the code doesn't check for err != nil before trying to assert the type of conn. If DialWithTimeout fails, it returns nil and an error. In that case, err != nil, and the type assertion fails because conn is nil.

A more general problem with this code is that a package should never panic without recovering and returning an error. It's especially egregious in a goroutine, since the caller can't recover.

**Comment by niemeyer** [comment]
Thanks for the report. Type-asserting is actually fine, but the problem is considering that the unknown value is a problem when err != nil. This has been fixed and released.

About your remark regarding panics, the situation of a "tcp" connection returning something else than a net.TCPConn should never ever happen, and the right thing to do here is indeed to panic harshly if this invariant is broken. It's easy to find similar usage cases in the standard library.

Again, thanks for the report.
