### ISSUE TITLE
Is it needed to close session at the end of main?

### ISSUE THREAD

**Issue by d3sire** [go-mgo/mgo#268]
I am using `mgo` with `goji` framework. I handle all sessions within each handler creating copy with `session.Copy()`. I am interested is there any real benefit to closing session at the end of main? For example:

    func main() {
         
        //setting up app. Master mongo session is created here
         app := New() 
         
        // some handles here 

        goji.Serve()

        //questions is if this is needed?
        defer app.Session.Close()
    }

Is this `Close()` call needed or go's garbage collector will reclaim all resources anyway at the end of program's execution?

**Comment by niemeyer** [comment]
Yes, it's a good practice to always follow the API, even if you plan to exist the process.

Please note that your line at the very end is a bit strange. It's deferring right before returning, which isn't doing much. As a better practice, defer right after you open the session, so that the logic closing the session is right next to the logic opening it, and so that early returns are handled properly.

**Comment by orangesoup** [comment]
@niemeyer What would be the best practice when I have a separate db package with a simple `Connect` method that I call right at the start of the main package? I can't defer right away in that function, that wouldn't work. How should I go around it? Honestly I've never closed the connection before, because I've never really found out what would be the best way to do it.

**Comment by niemeyer** [comment]
Why would it not work?

**Comment by orangesoup** [comment]
Well... maybe I'm missing something. I have a `db` package which looks like this:

```go
var S *mgo.Session

func Connect() {
	var err error
	S, err = mgo.Dial(...)
	if err != nil {
		log.Fatalln(err)
	}
	S.SetMode(mgo.Monotonic, true)
}
```

And in the `main` package I call the Connect function.

```go
func main() {
    db.Connect()
    ...
}
```

But if I add `defer S.Close()` to the `Connect` function it would simply close the connection right away.

**Comment by d3sire** [comment]
@niemeyer Thank your for the response. My question is similar to @orangesoup 's. I have a wrapper that calls `dial` and makes main session. I then copy this session in different functions and using `defer session.Close()` on copied sessions. But do I need to close the master session? And will `defer session.Close()` in a setup function work (much like in @orangesoup 's example). Thanks again for your time.

**Comment by niemeyer** [comment]
Yes, it should work just as usual for the main function. The problem and the solution are the same, either for the main section or for any of the others. In fact, there's nothing special about that "main session". You might just as well close the first one and keep the second, for example.

**Comment by orangesoup** [comment]
Let me get this straight then, it's still not quite clear for me yet, sorry. :) Basically I can close the first session right away with defer in the `Connect` function. At least that's what I understood. Later on I clone that session in a middleware and that's where it panics with `Session already closed`. So I'm guessing cloning a closed session is not working. 

How should I go around this?

**Comment by niemeyer** [comment]
There's no difference between the first and the Nth session. All of them need to be closed, and all of them cannot be used after being closed. So if you want to use a session, don't close it, and to close a session it's nice to be able to defer its closing right after creating it, but that's not a requirement. The only requirement is that it should eventually be closed.
