### ISSUE TITLE
Iter().Next(&result) is not exiting

### ISSUE THREAD

**Issue by rybit** [go-mgo/mgo#352]
I fully understand that this might be my error. 

``` go
	userQuery := bson.M{
		"reseller_id": nid,
		"created_at":  bson.M{"$gt": since},
	}
	user := map[string]interface{}{}
	for conn.C(userCollection).Find(userQuery).Iter().Next(&user) {
		fmt.Printf("user: %+v\n", user)
	}
```

This code is looping infinitely. There are only 3 users in that collection. The data is deserialized fine, but it doesn't seem to exit the loop. I would rather not use the `All` methods, but they might be my best option here. Any suggestions?

**Comment by niemeyer** [comment]
Hi Ryan,

That for loop will never end as long as you have even a single element in the collection, because every iteration of the loop it issues a new query and creates a new iterator. So it's looking at the same element over and over, very inefficiently.

Just store the iterator on a variable and use it in the loop, and the problem will go away.
