### ISSUE TITLE
Local time returned on decode

### ISSUE THREAD

**Issue by Syeberman** [go-mgo/mgo#362]
The BSON [timestamp decoder](https://github.com/go-mgo/mgo/blob/v2-unstable/bson/decode.go#L513) uses `time.Unix()` to create a `time.Time`.  It turns out that `time.Unix` returns a local time, which is surprising to receive from a database call.

Thankfully, you just need to call `t.UTC()` to convert this, which in a quick test appears to correctly handle the daylight-to-standard time overlap.  However, I feel it's important that a database engine should only return UTC times: you don't want the behaviour of your database to differ depending on whatever the server considers "local time".

**Comment by inancgumus** [comment]
I was having a problem with this in my tests and so, I fixed this and I created a pull request (globalsign/mgo#19) for this in https://github.com/globalsign/mgo. 

As in this repo, pull requests are not going to be merged because this repo has a lack of a maintainer right now (as you can see here: go-mgo/mgo/issues/416).
