### ISSUE TITLE
Please add new maintainers to this project,

### ISSUE THREAD

**Issue by asaf** [go-mgo/mgo#393]
@niemeyer 
There are 40 PR, few are critical and pending to be merged,

Please add new maintainers if you don't have time,

Thanks.

**Comment by niemeyer** [comment]
Which PR is critical and pending to be merged?

**Comment by niemeyer** [comment]
In either case, I apologize for your frustration with whatever you'd like to see handled and is not being. I'm happy to add more experienced and reliable maintainers that demonstrate capacity and long term interest to any projects I'm responsible for. I will not, though, add arbitrary people to the project simply because I don't have the time you'd like me to have for it. More important than keeping PR queues empty is to preserve its quality. A surprisingly large number of people depend on it.

If there are people you know of that have a proven track record and are interested in becoming long term maintainers please do let me know.

**Comment by asaf** [comment]
@niemeyer Sorry if the tone of this message was negative, no need to apologize, it was more a call for others to see whether there is someone who is interested with the right capabilities to assist. I totally agree, I personally prefer slow responses rather a project that gets error-prone and unmaintained due to inexperienced envolved personals over time, 

Here is, for example, a PR that blocks us from using mgo in production -- https://github.com/go-mgo/mgo/pull/367

Thanks.

**Comment by niemeyer** [comment]
There are issues in that modification in terms of what is going there, lacking tests, changes unrelated for the issue at hand (and incorrect). That's why I didn't merge it in the spot, and I apologize for taking a while to get to it. I'll merge it and address all of those before the next release.

**Comment by asaf** [comment]
@niemeyer Great, thanks.
