### ISSUE TITLE
Big CPU Usage Problem

### ISSUE THREAD

**Issue by skyhit** [go-mgo/mgo#403]
We we are doing heavy db operations, we faced a big CPU Usage problem (>95%), and when doing profiling, we saw a lot of cpu time is costed by https://github.com/go-mgo/mgo/blob/9a2573d4ae52a2bf9f5b7900a50e2f8bcceeb774/internal/scram/scram.go#L218

here is the description of our environment.

1. we are using MongoDB Atlas, so it have to strictly use SSL connection.
2. for each operation, we are always Copy the Session and Close it after usage.
3. if we removed the copy and close approach by maintaining the a limited list of connections, and using Ping() function to check available - similar approach as - https://gist.github.com/dagoof/47328f911fe220c9f73c, looks like the problem reduced.
4. any thought why the time usage for saltPassword is bigger?
5. is there a easy way to check session alive? I can not find any function.

**Comment by spencerjackson** [comment]
To provide security guarantees, MongoDB requires clients use lots of CPU to authenticate. mGo appears to do this work in the saltPassword you found. Because this cost is paid once when the connection is opened, this is no problem for clients which make connections and keep them alive for a long time.

Because you're tearing down and rebuilding connections, your client must spend time doing this work again and again. Reusing the connections, as you were in step 3, will save resources.

**Comment by skyhit** [comment]
@spencerjackson so why there is no a easy way to check if the session is alive?

**Comment by jyoon17** [comment]
This may be closely related to #254.

**Comment by skyhit** [comment]
the problem is solved.

**Comment by jyoon17** [comment]
@skyhit How did you solve it?

**Comment by ezeql** [comment]
@skyhit ^

**Comment by skyhit** [comment]
@ezeql I keeps the session and recovering from the session, instead of always creating new sessions

**Comment by haochun** [comment]
@skyhit hello,i occured the same problem.did you build the connection pool use self?
