### ISSUE TITLE
is it possible to get _id of last inserted document?

### ISSUE THREAD

**Issue by sydbarett07** [go-mgo/mgo#453]

**Comment by blocknotes** [comment]
IMO Insert should return the last id (like other mongo wrappers do); it's a pretty big issues to my eyes.

A workaround could be to set the _id in the insert using bson.NewObjectIdWithTime(time.Now()) - see [golang-mgo-why-does-mgo-not-return-the-id-of-inserted-document](https://stackoverflow.com/questions/12009312/golang-mgo-why-does-mgo-not-return-the-id-of-inserted-document) for details.

**Comment by dustywilson** [comment]
I very strongly disagree.  If you aren't going to use that ID, you shouldn't make the `mgo` client code do the effort to always get the MongoDB server to supply it back, especially if you're doing anything asynchronously.  If you _actually_ care about the ID value, generate it in your code using `bson.NewObjectID()` and then you already know what the ID will be before it ever hits the server.

**Comment by zygis** [comment]
Generate ID in client side when you have hundreds of servers - not safe at all...

**Comment by dannolan** [comment]
I'm inclined to agree depending on how you structure your collections you should defer to mongo to generate the IDs, even tho there is a tonne of entropy in the IDs.

**Comment by dustywilson** [comment]
If you are actually running hundreds of MongoDB servers, you will already know that you should be reducing as much server-wasted effort as possible, which is what this is.  You will also already know much about how this system actually works.  Or worse, if you're actually running *hundreds* of MongoDB servers, you might actually not know what you're doing because that's an unlikely thing to happen at all and you've got a serious performance issue on your hands.  If you just think you will need to scale to hundreds of servers, you're almost definitely optimizing for something that's very unlikely to occur, and certainly rather prematurely at that.

**Comment by dustywilson** [comment]
Sorry for the noise.  I didn't mean to submit that previous comment yet.

With regard to what "other mongo wrappers do", generally they secretly generate the ID for you if you didn't.  So it's still the database client generating the ID, even if you didn't do it in your code yourself.

https://docs.mongodb.com/manual/reference/method/db.collection.insert/ says it clearly: *"If the document does not specify an _id field, then MongoDB will add the _id field and assign a unique ObjectId for the document before inserting. Most drivers create an ObjectId and insert the _id field, but the mongod will create and populate the _id if the driver or application does not. If the document contains an _id field, the _id value must be unique within the collection to avoid duplicate key error."*

That is official guidance from the MongoDB project.  I believe they would have sufficient insight into how this database software works for this to be treated as truth.
