### ISSUE TITLE
Too little error reporting

### ISSUE THREAD

**Issue by kindlychung** [go-mgo/mgo#465]
The fact that code like the following can run is a bit disturbing:

```go
	session, err := mgo.Dial("127.0.0.1")
	if err != nil {
		panic(err)
	}
	c := session.DB("test").C("nonsense.nonsense.nowhere")
```

**Comment by Tri125** [comment]
That isn't an error and this has little to do with mgo. First if we look at the [doc](https://godoc.org/labix.org/v2/mgo#Database.C) we can understand that there's no way it could report an error because it involves no network communication.

However, as per mongoDB design, you can select a database or even collection that doesn't currently exists and it isn't an error. The db/collection will be created when you actually insert something in it.
https://docs.mongodb.com/manual/reference/method/db.getCollection/#behavior

> The collection specified may or may not exist on the server. If the collection does not exist, MongoDB creates it implicitly as part of write operations like db.collection.insertOne().
