### ISSUE TITLE
poollimit parameter is misleading users in common sense

### ISSUE THREAD

**Issue by pyloque** [go-mgo/mgo#467]
as I deep dived the source code, I could finally understand what the poollimit parameter means
```
poollimit = max(liveSockets-unusedSockets=working sockets)
```
it's really  wierd and misleading.

since usually in every library that we used, poollimit always means max(liveSockets)

if there are too many liveSockets, mgo never releases them

**Comment by vivace-io** [comment]
If sockets are not being released to the cache, that would tend to suggest that `Session.Close()` is not being called appropriately as documented. If you are calling this for every copied session, and you are running in to socket errors over time, what is your Mongo server version? I can't replicate, even in large numbers.

And, for the record, sockets are released only under certain circumstances, like abnormal socket terminations and so forth. Otherwise they are kept alive for re-use until the application exits, or the `mongod`/`mongos` server terminates it. (Usually 5-10 minutes depending on the host)

As to your interpretation of the source, I'm assuming you got that [this line of code](https://github.com/go-mgo/mgo/blob/9a2573d4ae52a2bf9f5b7900a50e2f8bcceeb774/server.go#L113), which ensures that the sum of all in-use and un-used sockets does not exceed the limit set forth to mgo. The maximum number of sockets is still "max(liveSockets)" under mgo.

**Comment by niemeyer** [comment]
You're probably expecting the pool limit functionality to be doing something it's not designed to do.

Per the documentation:
> SetPoolLimit sets the maximum number of sockets in use in a single server before this session will block waiting for a socket to be available. The default limit is 4096.

> This limit must be set to cover more than any expected workload of the application. It is a bad practice and an unsupported use case to use the database driver to define the concurrency limit of an application. Prevent such concurrency "at the door" instead, by properly restricting the amount of used resources and number of goroutines before they are created.

If you are hitting the pool limit, please increase it, or fix the application.
