### ISSUE TITLE
Replace bson.Getter and bson.Setter with bson.Marshaler and bson.Unmarshaler

### ISSUE THREAD

**Issue by mohamedattahri** [go-mgo/mgo#58]
Packages inside Go's encoding package all use interfaces named `Marshaler` and `Unmarshaler` to let developers provide their own encoding and decoding methods.

Is there any reason to use `Getter` and `Setter` instead?

**Comment by niemeyer** [comment]
With the bson package you get a value that should be marshaled in place of the original value, rather than doing the marshaling yourself. Thus, calling a "MarshalBSON" method that does not in fact marshal sounds slightly misleading.

That said, I'd probably use the Marshaler name nowadays, if only just because it's well known. It's not worth it right now, though. Compatibility with existing code is much more valuable.
