### ISSUE TITLE
Any txn.Op with non-existing Id and Assert set returns ErrAborted instead of ErrNotFound

### ISSUE THREAD

**Issue by dimitern** [go-mgo/mgo#64]
Consider the following:
```go
txn.Op{
  Id: "not-existing",           // any non-existing id
  Assert: D{{"life", "alive"}},
  Update: ...                   // unimportant
}
```

If you try to run a transaction with this Op, instead of the expected `mgo.ErrNotFound`, `txn.ErrAborted` is returned, which is slightly surprising. Perhaps the Id field has to be validated (e.g. by verifying the number of documents it matches is non-zero or even just 1) before evaluating the Assert clause, or at least before returning the final error in case of a `taborted` state.

Already reported on Launchpad as [#1403846](https://bugs.launchpad.net/mgo/+bug/1403846), it seems useful to have it here as well, in case somebody else might be affected.

**Comment by niemeyer** [comment]
This behavior is in line with the intended semantics: asserts fail with ErrAborted, always, and the fact a document is not present will not abort a transaction without an assertion. This behavior may be leveraged to implement useful semantics, although I do understand your desire to know exactly how a transaction failed. Unfortunately, there's a trade-off against consistency and simplicity in this case, and I'd rather not make the transaction package any more complex than it already is.

You can easily implement that on your side, though: once a transaction is aborted, just read the document _id to see if it is there. Of course, that might not be the real state of the document when the transaction was attempted, but this will be true either way if you consider the document non-existent (it may have been created since the transaction finished as well, for example).

**Comment by dimitern** [comment]
Thanks for the explanation @niemeyer !
