### ISSUE TITLE
Creating text index with weights

### ISSUE THREAD

**Issue by egonelbre** [go-mgo/mgo#65]
I'm unable to create a text index that contains weights. It seems that there simply isn't a way to specify it in [parseIndexKey](https://github.com/go-mgo/mgo/blob/v2/session.go#L975). *It also would be helpful to mention the key syntax `"[$<kind>:][-]<field name>"` in the documentation as well, I resorted to looking the source to find it.*

Also, while experimenting I wasn't able to create an index that [indexes all string fields](http://docs.mongodb.org/manual/tutorial/create-text-index-on-multiple-fields/#index-all-fields). I tried to do it with `c.EnsureIndex(mgo.Index{Key: []string{"$text:$**"})`. I expected it to have the same behavior as `db.collection.ensureIndex({ "$**": "text" }, {name:"$**"})`.

I also didn't understand why `EnsureIndex` didn't use the `index.Name` that has been passed as argument and used the generated name from fields instead. e.g. when calling as `c.EnsureIndex(mgo.Index{Name:"Hello", Key: []string{"$text:content"}})`. I expected it to use the `Name` and use the generated name, if `Name` wasn't provided.

**Comment by niemeyer** [comment]
Thanks for the comprehensive report, Egon. I'll split the response apart to be more easily processed:

Documentation
----

The $kind syntax is in fact part of the comprehensive [documentation of EnsureIndex](http://gopkg.in/mgo.v2#Collection.EnsureIndex).

Even then, I'll improve it further as you clearly have missed something there.

All fields index
----

The syntax you attempted is correct, and the fact it doesn't work is a bug. I'll fix it.

Weights
----

You are right, support for weights is missing. I'll fix that for the upcoming release as well.

Name
----

That behavior is [documented](http://godoc.org/gopkg.in/mgo.v2#Index), but there's no good reason to keep it. I'll make sure the name is used when provided.

**Comment by niemeyer** [comment]
While working on the feature, I changed my mind about whether supporting custom index names would be a good idea.  MongoDB only supports a single index with a given index key, so the custom name is a distraction. It will create surprising behavior where a given index is not created because a different index with the same key already exists, for example, and it breaks the use of current APIs, such as with DropIndex which is based on the index key.

All the remaining issues were addressed.
